namespace skeleton
{
	enum bones
	{
		amm = 0,
		loot = 1,
		spine1 = 2,
		spine2 = 3,
		spine3 = 4,
		neck = 5,
		Head = 6,
		head_end = 7,
		shoulder_L = 8,
		upper_arm_L = 9,
		lower_arm_L = 10,
		hand_L = 11,
		hand_L_end = 12,
		shoulder_R = 13,
		upper_arm_R = 14,
		lower_arm_R = 15,
		hand_R = 16,
		hand_R_end = 17,
		hip_L = 18,
		upper_leg_L = 19,
		lower_leg_L = 20,
		foot_l = 21,
		foot_L_end = 22,
		hip_R = 23,
		upper_leg_R = 24,
		lower_leg_R = 25,
		foot_r = 26,
		foot_R_end = 27,
		None = 28,
	};
	inline std::vector<std::pair<int, int>> Connections = {
						{neck, Head},
						{spine3, neck},
						{spine2, spine3},
						{spine1, spine2},
						{loot, spine1},
						{shoulder_R, spine3},
						{upper_arm_R, shoulder_R},
						{lower_arm_R, upper_arm_R},
						{hand_R, lower_arm_R},
						{shoulder_L, spine3},
						{upper_arm_L, shoulder_L},
						{lower_arm_L, upper_arm_L},
						{hand_L, lower_arm_L},
						{hip_R, loot},
						{upper_leg_R, hip_R},
						{lower_leg_R, upper_leg_R},
						{foot_r, lower_leg_R},
						{hip_L, loot},
						{upper_leg_L, hip_L},
						{lower_leg_L, upper_leg_L},
						{foot_l, lower_leg_L},
	};
};