#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BigPenController

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_BigPenController.BP_BigPenController_C
// 0x0008 (0x03D0 - 0x03C8)
class ABP_BigPenController_C final : public AAIController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_BigPenController(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BigPenController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BigPenController_C")
	}
	static class ABP_BigPenController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BigPenController_C>();
	}
};
DUMPER7_ASSERTS_ABP_BigPenController_C;

SDK_NAMESPACE_END
