#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CrouchingCheck

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Mover_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CrouchingCheck.BP_CrouchingCheck_C
// 0x0008 (0x0048 - 0x0040)
class UBP_CrouchingCheck_C final : public UBaseMovementModeTransition
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0040(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void Trigger(const struct FSimulationTickParams& Params_Trigger);
	void K2_OnRegistered();
	void ExecuteUbergraph_BP_CrouchingCheck(int32 EntryPoint);

	struct FTransitionEvalResult Evaluate(const struct FSimulationTickParams& Params_Evaluate) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CrouchingCheck_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CrouchingCheck_C")
	}
	static class UBP_CrouchingCheck_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CrouchingCheck_C>();
	}
};
DUMPER7_ASSERTS_UBP_CrouchingCheck_C;

SDK_NAMESPACE_END
