#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Container_Base

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_EnvironmentSystem_DamagedSpawn_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EnvironmentSystem_Container_Base.BP_EnvironmentSystem_Container_Base_C
// 0x0048 (0x03A8 - 0x0360)
class ABP_EnvironmentSystem_Container_Base_C : public ABP_EnvironmentSystem_DamagedSpawn_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_EnvironmentSystem_Container_Base_C; // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                BoundSize;                                         // 0x0368(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TSoftObjectPtr<class UBP_RBD_VAT_DataAssets_C> VATData_Asset;                                    // 0x0380(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_EnvironmentSystem_Container_Base(int32 EntryPoint);
	void ReceiveDestroyed();
	void ReplicateEvent();
	void SpawnMaterial();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EnvironmentSystem_Container_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EnvironmentSystem_Container_Base_C")
	}
	static class ABP_EnvironmentSystem_Container_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EnvironmentSystem_Container_Base_C>();
	}
};
DUMPER7_ASSERTS_ABP_EnvironmentSystem_Container_Base_C;

SDK_NAMESPACE_END
