#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Tree_Sand

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_EnvironmentSystem_Tree_Sand.BP_EnvironmentSystem_Tree_Sand_C.ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand
// 0x0020 (0x0020 - 0x0000)
struct BP_EnvironmentSystem_Tree_Sand_C_ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_EnvironmentSystem_Tree_Sand_C_ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
