#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Tree

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_EnvironmentSystem_DamagedSpawn_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EnvironmentSystem_Tree.BP_EnvironmentSystem_Tree_C
// 0x0010 (0x0370 - 0x0360)
class ABP_EnvironmentSystem_Tree_C final : public ABP_EnvironmentSystem_DamagedSpawn_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_EnvironmentSystem_Tree_C;        // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          LogState;                                          // 0x0368(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void SpawnMaterial();
	void ReplicateEvent();
	void ReceiveDestroyed();
	void ExecuteUbergraph_BP_EnvironmentSystem_Tree(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EnvironmentSystem_Tree_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EnvironmentSystem_Tree_C")
	}
	static class ABP_EnvironmentSystem_Tree_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EnvironmentSystem_Tree_C>();
	}
};
DUMPER7_ASSERTS_ABP_EnvironmentSystem_Tree_C;

SDK_NAMESPACE_END
