#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Ruins

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_EnvironmentSystem_DamagedSpawn_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EnvironmentSystem_Ruins.BP_EnvironmentSystem_Ruins_C
// 0x0018 (0x0378 - 0x0360)
class ABP_EnvironmentSystem_Ruins_C final : public ABP_EnvironmentSystem_DamagedSpawn_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_EnvironmentSystem_Ruins_C;       // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBillboardComponent*                    SpawnPosition2;                                    // 0x0368(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBillboardComponent*                    SpawnPosition1;                                    // 0x0370(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void SpawnMaterial();
	void ReplicateEvent();
	void ReceiveDestroyed();
	void ExecuteUbergraph_BP_EnvironmentSystem_Ruins(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EnvironmentSystem_Ruins_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EnvironmentSystem_Ruins_C")
	}
	static class ABP_EnvironmentSystem_Ruins_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EnvironmentSystem_Ruins_C>();
	}
};
DUMPER7_ASSERTS_ABP_EnvironmentSystem_Ruins_C;

SDK_NAMESPACE_END
