#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EnvironmentSystem_Tree_Sand

#include "Basic.hpp"

#include "BP_EnvironmentSystem_Tree_Sand_classes.hpp"
#include "BP_EnvironmentSystem_Tree_Sand_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_EnvironmentSystem_Tree_Sand.BP_EnvironmentSystem_Tree_Sand_C.SpawnMaterial
// (BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Tree_Sand_C::SpawnMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Tree_Sand_C", "SpawnMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Tree_Sand.BP_EnvironmentSystem_Tree_Sand_C.ReplicateEvent
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)

void ABP_EnvironmentSystem_Tree_Sand_C::ReplicateEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Tree_Sand_C", "ReplicateEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Tree_Sand.BP_EnvironmentSystem_Tree_Sand_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_EnvironmentSystem_Tree_Sand_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Tree_Sand_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EnvironmentSystem_Tree_Sand.BP_EnvironmentSystem_Tree_Sand_C.ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EnvironmentSystem_Tree_Sand_C::ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EnvironmentSystem_Tree_Sand_C", "ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand");

	Params::BP_EnvironmentSystem_Tree_Sand_C_ExecuteUbergraph_BP_EnvironmentSystem_Tree_Sand Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
