#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LINK_Manequin

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_LINK_Manequin.BP_LINK_Manequin_C.ExecuteUbergraph_BP_LINK_Manequin
// 0x0010 (0x0010 - 0x0000)
struct BP_LINK_Manequin_C_ExecuteUbergraph_BP_LINK_Manequin final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_LINK_Manequin_C_ExecuteUbergraph_BP_LINK_Manequin;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
