#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReplicateEventController

#include "Basic.hpp"

#include "EN_DamageType_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ReplicateEventController.BP_ReplicateEventController_C
// 0x0010 (0x02B8 - 0x02A8)
class ABP_ReplicateEventController_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_ReplicateEventController(int32 EntryPoint);
	void ApplyDamage(class UObject* ターゲット, double DamageValue, int32 TeamIndex, EN_DamageType DamageType, const struct FTransform& SourceAgentPoint, bool UnAvoidable, class FName DamageName);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ReplicateEventController_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ReplicateEventController_C")
	}
	static class ABP_ReplicateEventController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ReplicateEventController_C>();
	}
};
DUMPER7_ASSERTS_ABP_ReplicateEventController_C;

SDK_NAMESPACE_END
