#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_DampingControl

#include "Basic.hpp"

#include "BPC_DampingControl_classes.hpp"
#include "BPC_DampingControl_parameters.hpp"


SDK_NAMESPACE_START

// Function BPC_DampingControl.BPC_DampingControl_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UBPC_DampingControl_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_DampingControl_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPC_DampingControl.BPC_DampingControl_C.ExecuteUbergraph_BPC_DampingControl
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPC_DampingControl_C::ExecuteUbergraph_BPC_DampingControl(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPC_DampingControl_C", "ExecuteUbergraph_BPC_DampingControl");

	Params::BPC_DampingControl_C_ExecuteUbergraph_BPC_DampingControl Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
