#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_RayPositions

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_RayPositions.BPC_RayPositions_C
// 0x0020 (0x00D8 - 0x00B8)
class UBPC_RayPositions_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<struct FTransform>                     ChildRelativeTransform;                            // 0x00C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class AActor*                                 OwnerActor;                                        // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void SetUpTransforms();
	void ReceiveBeginPlay();
	void GetRayPositions(TArray<struct FVector>* VectorArray);
	void ExecuteUbergraph_BPC_RayPositions(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_RayPositions_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_RayPositions_C")
	}
	static class UBPC_RayPositions_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_RayPositions_C>();
	}
};
DUMPER7_ASSERTS_UBPC_RayPositions_C;

SDK_NAMESPACE_END
