#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPC_CastRootPrimitiveComp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPC_CastRootPrimitiveComp.BPC_CastRootPrimitiveComp_C
// 0x0010 (0x00C8 - 0x00B8)
class UBPC_CastRootPrimitiveComp_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPrimitiveComponent*                    PrimitiveComp;                                     // 0x00C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BPC_CastRootPrimitiveComp(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPC_CastRootPrimitiveComp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPC_CastRootPrimitiveComp_C")
	}
	static class UBPC_CastRootPrimitiveComp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPC_CastRootPrimitiveComp_C>();
	}
};
DUMPER7_ASSERTS_UBPC_CastRootPrimitiveComp_C;

SDK_NAMESPACE_END
