#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_TraceEnd

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTTask_TraceEnd.BTTask_TraceEnd_C
// 0x0008 (0x00B0 - 0x00A8)
class UBTTask_TraceEnd_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveExecuteAI(class AAIController* OwnerController_ReceiveExecuteAI, class APawn* ControlledPawn_ReceiveExecuteAI);
	void ExecuteUbergraph_BTTask_TraceEnd(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTTask_TraceEnd_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTTask_TraceEnd_C")
	}
	static class UBTTask_TraceEnd_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTTask_TraceEnd_C>();
	}
};
DUMPER7_ASSERTS_UBTTask_TraceEnd_C;

SDK_NAMESPACE_END
