#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_Trace

#include "Basic.hpp"

#include "BTTask_Trace_classes.hpp"
#include "BTTask_Trace_parameters.hpp"


SDK_NAMESPACE_START

// Function BTTask_Trace.BTTask_Trace_C.ExecuteUbergraph_BTTask_Trace
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBTTask_Trace_C::ExecuteUbergraph_BTTask_Trace(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_Trace_C", "ExecuteUbergraph_BTTask_Trace");

	Params::BTTask_Trace_C_ExecuteUbergraph_BTTask_Trace Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BTTask_Trace.BTTask_Trace_C.ReceiveExecuteAI
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AAIController*                    OwnerController_ReceiveExecuteAI                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            ControlledPawn_ReceiveExecuteAI                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBTTask_Trace_C::ReceiveExecuteAI(class AAIController* OwnerController_ReceiveExecuteAI, class APawn* ControlledPawn_ReceiveExecuteAI)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BTTask_Trace_C", "ReceiveExecuteAI");

	Params::BTTask_Trace_C_ReceiveExecuteAI Parms{};

	Parms.OwnerController_ReceiveExecuteAI = OwnerController_ReceiveExecuteAI;
	Parms.ControlledPawn_ReceiveExecuteAI = ControlledPawn_ReceiveExecuteAI;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
