#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LBPC_Glue

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass LBPC_Glue.LBPC_Glue_C
// 0x0030 (0x0270 - 0x0240)
class ULBPC_Glue_C final : public USceneComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0240(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPrimitiveComponent*                    OwnerPrimitive;                                    // 0x0248(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPhysicsConstraintComponent*            ConstraintComp;                                    // 0x0250(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<struct FVector>                        AttachPositions;                                   // 0x0258(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void UniqueFillter(TArray<struct FHitResult>& HitRezults, TArray<struct FHitResult>* Out);
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveBeginPlay();
	void ExecuteUbergraph_LBPC_Glue(int32 EntryPoint);
	void DoConnect(const struct FHitResult& HitRezult1, const struct FHitResult& HitRezult2);
	void ConstraintSetup(class UPhysicsConstraintComponent* ConstraintComponent);
	void Connect();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LBPC_Glue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LBPC_Glue_C")
	}
	static class ULBPC_Glue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULBPC_Glue_C>();
	}
};
DUMPER7_ASSERTS_ULBPC_Glue_C;

SDK_NAMESPACE_END
