#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MiniPenguinWeight

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MiniPenguinWeight.WBP_MiniPenguinWeight_C
// 0x0018 (0x0358 - 0x0340)
class UWBP_MiniPenguinWeight_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0340(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             TextBlock_86;                                      // 0x0348(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_0;                                           // 0x0350(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetText(const class FText& Text, int32 Index_0);
	void SetColor(const struct FLinearColor& Color, int32 Index_0);
	void PlayAnimationMessage(bool IsForward, int32 Index_0);
	void ExecuteUbergraph_WBP_MiniPenguinWeight(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MiniPenguinWeight_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MiniPenguinWeight_C")
	}
	static class UWBP_MiniPenguinWeight_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MiniPenguinWeight_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MiniPenguinWeight_C;

SDK_NAMESPACE_END
