#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DamagedOutLine

#include "Basic.hpp"

#include "WBP_DamagedOutLine_classes.hpp"
#include "WBP_DamagedOutLine_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_DamagedOutLine.WBP_DamagedOutLine_C.ExecuteUbergraph_WBP_DamagedOutLine
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_DamagedOutLine_C::ExecuteUbergraph_WBP_DamagedOutLine(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamagedOutLine_C", "ExecuteUbergraph_WBP_DamagedOutLine");

	Params::WBP_DamagedOutLine_C_ExecuteUbergraph_WBP_DamagedOutLine Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_DamagedOutLine.WBP_DamagedOutLine_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_DamagedOutLine_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamagedOutLine_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_DamagedOutLine.WBP_DamagedOutLine_C.AnimationEnd
// (BlueprintCallable, BlueprintEvent)

void UWBP_DamagedOutLine_C::AnimationEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_DamagedOutLine_C", "AnimationEnd");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
